---
title: "Untitled"
author: "Diezhang WU"
date: "12/1/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(SuperLearner)
library(ltmle)
library(MASS)
library(dplyr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
data <-read.csv("fertility_sperm.csv")
colnames(data)

data <- data %>% 
  mutate(W11 = age,
         W12 = sitting_hour,
         W13 = trauma,
         W14 = case_when(alcohol<0.8 ~ "2",
                         alcohol==0.8 ~ "1",
                         alcohol==1 ~ "0"),
         W2 = case_when(season==-1 ~ 'Winter',
                        season==-0.33 ~'Spring',
                        season==0.33 ~ 'Summer',
                        season==1 ~ 'Fall'),
         A = case_when(smoking==-1 ~ 0,
                       smoking==0 ~ 1,
                       smoking==1 ~ 1),
         Y = ifelse(diagnosis=='N',1,0))

ObsData <- data %>% dplyr::select(W11, W12, W13, W14, W2, A, Y)

```


```{r}
table(ObsData[which(ObsData$A == 1),]$W13, ObsData[which(ObsData$A == 1),]$W14)
table(ObsData[which(ObsData$A == 0),]$W13, ObsData[which(ObsData$A == 0),]$W14)
```




```{r}
## substitution estimator
reg.model <- glm(Y ~ A + W11 + W12 + W13 + W14 + W2, family = "binomial", data = ObsData)
txt <- control <- ObsData
txt$A <- 1
control$A <- 0
predictY.txt <- predict(reg.model, newdata = txt, type = "response")
predictY.control <- predict(reg.model, newdata = control, type = "response")
estimate.ss <- mean(predictY.txt - predictY.control)
estimate.ss
```
```{r}
## IPTW estimator
prob.AW.reg <- glm(A ~W11 + W12 + W13 + W14, family = "binomial", data = ObsData)
probs.1W <- predict(prob.AW.reg, type = "response")
probs.0W <- 1 - probs.1W
summary(probs.1W)
summary(probs.0W)

wt1 <- as.numeric(ObsData$A == 1) / probs.1W
wt0 <- as.numeric(ObsData$A == 0) / probs.0W
summary(wt1)
summary(wt0)

IPTW <- mean(wt1*ObsData$Y - wt0*ObsData$Y)
IPTW
```


```{r}
## TMLE estimator with superlerner
## SS with TMLE
library("SuperLearner")
SL.library <- c("SL.mean", "SL.glm", "SL.step.interaction")

X <- subset(ObsData, select = c(A, W11, W12, W13, W14, W2))
X1 <- X0 <- X
X1$A <- 1
X0$A <- 0

SL.outcome <- SuperLearner(Y = ObsData$Y, X = X, family = "binomial", SL.library = SL.library)
SL.outcome

expY.givenAW <- predict(SL.outcome, newdata=X)$pred
expY.given1W <- predict(SL.outcome, newdata=X1)$pred
expY.given0W <- predict(SL.outcome, newdata=X0)$pred

tail(data.frame(A=ObsData$A, expY.givenAW, expY.given1W, expY.given0W))

PsiHat.SS<-mean(expY.given1W - expY.given0W)
PsiHat.SS


## IPTW with TLME
X <- subset(ObsData, select= -c(A,Y))
SL.exposure<- SuperLearner(Y=ObsData$A, X=X[,-ncol(X)], SL.library=SL.library, family="binomial")
SL.exposure
probA1.givenW<- SL.exposure$SL.predict
# above is equivalent to
# check <- predict(SL.exposure, newdata=X)$pred
# sum(probA1.givenW != check)
probA0.givenW<- 1- probA1.givenW


H.AW<- as.numeric(ObsData$A==1)/probA1.givenW - as.numeric(ObsData$A==0)/probA0.givenW
# also want to evaluate the clever covariates at A=1 and A=0 for all participants
H.1W<- 1/probA1.givenW
H.0W<- -1/probA0.givenW
tail(data.frame(ObsData$A, H.AW, H.1W, H.0W))
PsiHat.IPTW <-mean( H.AW*ObsData$Y)
PsiHat.IPTW

## TMLE estimator
logitUpdate<- glm(ObsData$Y ~ -1 +offset(qlogis(expY.givenAW)) + H.AW, family='binomial')
epsilon <- logitUpdate$coef
epsilon
expY.givenAW.star<- plogis(qlogis(expY.givenAW)+ epsilon*H.AW)
expY.given1W.star<- plogis(qlogis(expY.given1W)+ epsilon*H.1W)
expY.given0W.star<- plogis(qlogis(expY.given0W)+ epsilon*H.0W)
coef(glm(ObsData$Y ~ -1 +offset(qlogis(expY.givenAW.star)) + H.AW, family=binomial))
PsiHat.TMLE <- mean(expY.given1W.star - expY.given0W.star)

c(PsiHat.SS, PsiHat.IPTW, PsiHat.TMLE)



CV.SL.out<- CV.SuperLearner(Y=ObsData$Y, X=X, V = 20, SL.library=SL.library, family='binomial')
summary(CV.SL.out)
CV.SL.out$AllSL
CV.SL.out$coef
```



```{r}
summary(data.frame(probA1.givenW, probA0.givenW))
```







