---
title: "Ariane-Analysis"
author: "Ariane Stark"
date: "11/29/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(SuperLearner)
library(ltmle)
library(MASS)
library(dplyr)
library(kableExtra)
library(caret)
library(randomForest)
knitr::opts_chunk$set(echo = FALSE)
```


```{r include=FALSE}
data <-read.csv("fertility_sperm.csv")
colnames(data)

data <- data %>% 
  mutate(W11 = age,
         W12 = sitting_hour,
         W13 = trauma,
         W14 = case_when(alcohol<0.8 ~ '2',
                         alcohol==0.8 ~ '1',
                         alcohol==1 ~ '0'),
         W2 = case_when(season==-1 ~ 'Fall/Winter',
                        season==-0.33 ~'Spring/Summer',
                        season==0.33 ~ 'Spring/Summer',
                        season==1 ~ 'Fall/Winter'),
         A = case_when(smoking==-1 ~ 0,
                       smoking==0 ~ 1,
                       smoking==1 ~ 1),
         Y = ifelse(diagnosis=='N',1,0))

ObsData <- data %>% dplyr::select(W11, W12, W13, W14, W2, A, Y)
```


```{r include=FALSE}
table(ObsData$W13,ObsData$Y,ObsData$A)

table(ObsData$W14,ObsData$Y,ObsData$A)

table(ObsData$W2,ObsData$Y,ObsData$A)


table(ObsData$W13,ObsData$W14,ObsData$A)
```


# Parametric G-Comp

```{r}

reg.model<- glm(Y ~ W11 + W12 + W13 + W14 + W2 + A
                + A*W11 + A*W12 + A*W13 + A*W14, 
                family='binomial', data=ObsData)

txt<- control <- ObsData

txt$A <-1
control$A <- 0

predictY.txt<- predict(reg.model, newdata = txt, type='response')
predictY.control<- predict(reg.model, newdata = control, type='response')

mean(predictY.txt - predictY.control)


```




# IPTW
```{r}
prob.AW.reg<- glm(A ~ W11 + W12 + W13 + W14, 
                  family="binomial", data=ObsData)
prob.1W <- predict(prob.AW.reg, type= "response")
prob.0W <- 1 - prob.1W


wt1 <- as.numeric(ObsData$A==1)/prob.1W
wt0 <- as.numeric(ObsData$A==0)/prob.0W

summary(wt1)
summary(wt0)

IPTW<- mean( wt1*ObsData$Y) -  mean( wt0*ObsData$Y)
IPTW
```
Over 50% of wt1 are zero

The IPTW estimate of $\Psi(\mathbb{P}_0)=$ `r paste0(IPTW*100,"%)`


# Stabilized IPTW - Modified Horvitz Thompson

```{r}
MHT <- mean( wt1*ObsData$Y)/mean( wt1) -  mean( wt0*ObsData$Y)/mean( wt0)
MHT
```


# Superlearner

```{r message=FALSE, warning=FALSE}
set.seed(123)

X<- subset(ObsData, select= -Y )

SL.library<- c('SL.glm', 'SL.glm.interaction', "SL.step",
               "SL.randomForest","SL.step.forward","SL.stepAIC","SL.mean")

SL.out<- SuperLearner(Y=ObsData$Y, X=X, SL.library=SL.library,
                      family='binomial', 
                      cvControl=list(V=10,stratifyCV=TRUE),
                      verbose = FALSE)

SL.out

#SL.out$SL.predict

mean( (ObsData$Y- SL.out$SL.predict)^2)
```


```{r message=FALSE, warning=FALSE}
CV.SL.out<- CV.SuperLearner(Y=ObsData$Y, X=X, 
                            SL.library=SL.library, family='binomial',
                            cvControl = list(V = 5), 
                            innerCvControl = list(list(V = 20)))

summary(CV.SL.out)

CV.SL.out$coef


CV.SL.out$whichDiscrete
```
Random forest had bets performance in 2 calls and step aic in the other 3


Random seeds seem to alternate around rf, step aic, and step forward


# TMLE

```{r message=FALSE, warning=FALSE}
ltmle.SL<- ltmle(data=ObsData, Anodes='A', Ynodes='Y', abar=list(1,0),
                 SL.library=SL.library)
summary(ltmle.SL)

```
```{r}
set.seed(123)
run.tmle <- function(ObsData, SL.library){
  
  #------------------------------------------
  # Simple substitution estimator 
  #------------------------------------------

  # dataframe X with baseline covariates and exposure
  X <- subset(ObsData, select=c(A, W11, W12, W13, W14,W2))
  
  # set the exposure=1 in X1 and the exposure=0 in X0
  X1 <- X0 <- X
  X1$A <- 1 	# exposed ('good guy')
  X0$A <- 0	# unexposed (not a 'good guy')
  
  # Estimate E_0(Y|A,W) with Super Learner
  SL.outcome <- SuperLearner(Y=ObsData$Y, X=X, SL.library=SL.library, 
                             family="binomial")
  
  # get the expected outcome, given the observed exposure and covariates
  expY.givenAW <- predict(SL.outcome, newdata=ObsData)$pred
  # expected outcome, given A=1 and covariates 
  expY.given1W <- predict(SL.outcome, newdata=X1)$pred
  # expected outcome, given A=0 and covariates
  expY.given0W <- predict(SL.outcome, newdata=X0)$pred
  
  # simple substitution estimator would be 
  PsiHat.SS <- mean(expY.given1W - expY.given0W)
  
  #------------------------------------------
  # Inverse probability of txt weighting
  #------------------------------------------
  
  #  Super Learner for the exposure mechanism  P_0(A=1|W)
  SL.exposure <- SuperLearner(Y=ObsData$A, 
                              X=subset(ObsData, select= -c(A,Y,W2)),
                              SL.library=SL.library, family="binomial")
  
  # generate the predicted prob of being exposed, given baseline cov
  probA1.givenW <- SL.exposure$SL.predict
  # generate the predicted prob of not being exposed, given baseline cov
  probA0.givenW <- 1- probA1.givenW
  
  # clever covariate
  H.AW <- as.numeric(ObsData$A==1)/probA1.givenW - as.numeric(ObsData$A==0)/probA0.givenW
  
  # also want to evaluate the clever covariate at A=1 and A=0 for all participants
  H.1W <- 1/probA1.givenW
  H.0W <- -1/probA0.givenW
  
  # IPTW estimate
  PsiHat.IPTW <- mean(H.AW*ObsData$Y)
  
  #------------------------------------------
  # Targeting & TMLE
  #------------------------------------------
  
  # Update the initial estimator of E_0(Y|A,W)
  # run logistic regression of Y on H.AW using the logit of the esimates as offset
  logitUpdate<- glm( ObsData$Y ~ -1 +offset(qlogis(expY.givenAW)) + 
                       H.AW, family='binomial')
  epsilon <- logitUpdate$coef
  
  # obtain the targeted estimates
  expY.givenAW.star<- plogis( qlogis(expY.givenAW)+ epsilon*H.AW )  
  expY.given1W.star<- plogis( qlogis(expY.given1W)+ epsilon*H.1W )	
  expY.given0W.star<- plogis( qlogis(expY.given0W)+ epsilon*H.0W )
  
  # TMLE point estimate
  PsiHat.TMLE<- mean(expY.given1W.star - expY.given0W.star)
  
  #------------------------------------------
  # Return a list withthe point estimates, targeted estimates of E_0(Y|A,W), 
  # and the vector of clever covariates
  #------------------------------------------
  
  estimates <- data.frame(cbind(PsiHat.SS=PsiHat.SS, PsiHat.IPTW, PsiHat.TMLE))
  predictions <- data.frame(cbind(expY.givenAW.star, expY.given1W.star, expY.given0W.star))
  colnames(predictions) <- c('givenAW', 'given1W', 'given0W')
  list(estimates=estimates, predictions=predictions, H.AW=H.AW)
}
```


```{r}
out <- run.tmle(ObsData = ObsData, SL.library = SL.library)
est <- out$estimates
est

```


