---
title: "Final Project"
author: "Minsu Kim"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(SuperLearner)
# library(ltmle)
library(MASS)
library(dplyr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
data <-read.csv("fertility_sperm.csv")
# colnames(data)
# table(data$trauma)
data <- data %>% 
  mutate(W11 = age,   #numerical
         W12 = sitting_hour, #numerical
         W13 = trauma,   # 0/1
         W14 = case_when(alcohol<0.8 ~ '2',
                         alcohol==0.8 ~ '1',
                         alcohol==1 ~ '0'),
         W2 = case_when(season==-1 ~ 'Fall/Winter',
                        season==-0.33 ~'Spring/Summer',
                        season==0.33 ~ 'Spring/Summer',
                        season==1 ~ 'Fall/Winter'),
         A = case_when(smoking==-1 ~ 0,
                       smoking==0 ~ 1,
                       smoking==1 ~ 1),
         Y = ifelse(diagnosis=='N',1,0))
ObsData <- data %>% dplyr::select(W11, W12, W13, W14, W2, A, Y)
```

```{r}
table(data$alcohol)
table(data$smoking)

table(ObsData$W13, ObsData$W14, ObsData$A)
```


```{r SS, warning=FALSE}
# Simple substitution estimator based on the G-computation formula:
library("SuperLearner")
# specify the library
set.seed(123)
SL.library<- c("SL.mean", "SL.glm", "SL.step.interaction", "SL.randomForest")

X0 <- X1 <- X <- ObsData[ , -7]
X1$A <- 1
X0$A <- 0

#Estimate E0(Y|A;W) by running SuperLearner. Call this object SL.outcome.
SL.outcome<- SuperLearner(Y=ObsData$Y, X=X, SL.library=SL.library, family="binomial")
expY.givenAW <- predict(SL.outcome, newdata=X)$pred
expY.given1W<- predict(SL.outcome, newdata=X1)$pred
expY.given0W<- predict(SL.outcome, newdata=X0)$pred

PsiHat.SS <- sum(expY.given1W - expY.given0W)/100

PsiHat.SS
```


```{r IPTW, warning=FALSE}
#IPTW
#Estimate P_0(A = 1|W) by running SuperLearner. Call this object SL.exposure. (Lab5, 3(a))q
set.seed(123)
X <- subset(ObsData, select= -c(W2,A,Y))
SL.exposure <- SuperLearner(Y=ObsData$A, X=X, 
                           SL.library=SL.library, family="binomial")

probA1.givenW <- SL.exposure$SL.predict
probA0.givenW <- 1 - probA1.givenW

H.AW<- as.numeric(ObsData$A==1)/probA1.givenW - as.numeric(ObsData$A==0)/probA0.givenW
H.1W<- 1/probA1.givenW
H.0W<- -1/probA0.givenW
PsiHat.IPTW <-mean( H.AW*ObsData$Y)
PsiHat.IPTW
```

```{r}
summary(data.frame(probA1.givenW, probA0.givenW))
```


```{r IPTW2, include=FALSE}
# OR 
wt1 <- as.numeric(ObsData$A==1)/probA1.givenW
wt0 <- as.numeric(ObsData$A==0)/probA0.givenW
summary(wt1)
summary(wt0)
mean(wt1*ObsData$Y) - mean(wt0*ObsData$Y)
```

```{r unadjusted}
# unadjusted estimator
unadj <- mean(ObsData[ObsData$A==1, 'Y']) - mean(ObsData[ObsData$A==0, 'Y'])
unadj
```



```{r TMLE, warning=FALSE}
logitUpdate<- glm(ObsData$Y ~ -1 +offset(qlogis(expY.givenAW)) + H.AW, family='binomial')

epsilon<- logitUpdate$coef

# obtain the targeted estimates
expY.givenAW.star<- plogis(qlogis(expY.givenAW)+ epsilon*H.AW)
expY.given1W.star<- plogis(qlogis(expY.given1W)+ epsilon*H.1W)
expY.given0W.star<- plogis(qlogis(expY.given0W)+ epsilon*H.0W)

PsiHat.TMLE <- mean(expY.given1W.star- expY.given0W.star)
PsiHat.TMLE
```


```{r comparison}
# comparing the estimates...
c(PsiHat.SS, PsiHat.IPTW, unadj, PsiHat.TMLE)
```


```{r CV risk}
# Assessment of the performance (i.e., cross-validated risk estimates)
set.seed(123)

X<- subset(ObsData, select= -Y )
SL.out<- SuperLearner(Y=ObsData$Y, X=X, SL.library=SL.library, cvControl=list(V=20))
SL.out
```

```{r}
CV.SL.out<- CV.SuperLearner(Y=ObsData$Y, X=X, V = 20, SL.library=SL.library, family='binomial')
summary(CV.SL.out)
```








